import type { ProviderModel } from "@v2/plugin-contracts";
import type { ProviderConnection } from "@v2/provider-contracts";
export class ProviderRepository {
  constructor(private readonly db: D1Database) {}
  private map(row: { id: string; workspace_id: string; provider_id: string; title: string; status: ProviderConnection["status"]; default_model_id: string | null }): ProviderConnection { return { id: row.id, workspaceId: row.workspace_id, providerId: row.provider_id, title: row.title, status: row.status, defaultModelId: row.default_model_id }; }
  async list(workspaceId: string): Promise<ProviderConnection[]> { const rows = await this.db.prepare("SELECT id, workspace_id, provider_id, title, status, default_model_id FROM provider_connections WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all<{ id: string; workspace_id: string; provider_id: string; title: string; status: ProviderConnection["status"]; default_model_id: string | null }>(); return rows.results.map((row) => this.map(row)); }
  async get(connectionId: string): Promise<ProviderConnection | undefined> { const row = await this.db.prepare("SELECT id, workspace_id, provider_id, title, status, default_model_id FROM provider_connections WHERE id = ?").bind(connectionId).first<{ id: string; workspace_id: string; provider_id: string; title: string; status: ProviderConnection["status"]; default_model_id: string | null }>(); return row ? this.map(row) : undefined; }
  async createWorkersAi(workspaceId: string, title: string, modelId: string, configured: boolean): Promise<ProviderConnection> { const id = `${workspaceId}.${crypto.randomUUID()}`; const status = configured ? "configured" as const : "unavailable" as const; await this.db.prepare("INSERT INTO provider_connections (id, workspace_id, provider_id, title, status, default_model_id) VALUES (?, ?, 'cloudflare-workers-ai', ?, ?, ?)").bind(id, workspaceId, title, status, modelId).run(); return { id, workspaceId, providerId: "cloudflare-workers-ai", title, status, defaultModelId: modelId }; }
  async replaceModels(connectionId: string, models: ProviderModel[]): Promise<void> { await this.db.batch([this.db.prepare("DELETE FROM provider_model_snapshots WHERE connection_id = ?").bind(connectionId), ...models.map((model) => this.db.prepare("INSERT INTO provider_model_snapshots (id, connection_id, model_id, title, capabilities_json) VALUES (?, ?, ?, ?, ?)").bind(crypto.randomUUID(), connectionId, model.id, model.title, JSON.stringify(model.capabilities)))]); }
}
