#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { apiEndpoints } from "../packages/api-contracts/src/index.ts";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const generatedDir = join(root, "generated", "openapi");
const clientPath = join(root, "packages", "api-client", "src", "generated.ts");
const check = process.argv.includes("--check");

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function pathWithOpenApiParams(path) {
  return path.replace(/\{([^}]+)\}/g, "{$1}");
}

function schema(value) {
  try {
    return typeof z.toJSONSchema === "function" ? z.toJSONSchema(value) : {};
  } catch {
    return {};
  }
}

function requestBody(endpoint) {
  if (endpoint.method === "GET" || endpoint.method === "HEAD") return undefined;
  return { required: false, content: { "application/json": { schema: schema(endpoint.body) } } };
}

function parameters(endpoint) {
  const params = [];
  for (const name of [...endpoint.path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1])) {
    params.push({ name, in: "path", required: true, schema: { type: "string" } });
  }
  const queryShape = endpoint.query?._def?.shape;
  const query = typeof queryShape === "function" ? queryShape() : queryShape;
  if (query && typeof query === "object") {
    for (const name of Object.keys(query)) params.push({ name, in: "query", required: false, schema: { type: "string" } });
  }
  return params;
}

function openApi(service) {
  const paths = {};
  for (const endpoint of apiEndpoints.filter((item) => item.service === service)) {
    const path = pathWithOpenApiParams(endpoint.path);
    paths[path] ??= {};
    paths[path][endpoint.method.toLowerCase()] = {
      operationId: endpoint.operationId,
      security: endpoint.auth === "anonymous" ? [] : [{ cookieAuth: [] }],
      parameters: parameters(endpoint),
      ...(requestBody(endpoint) ? { requestBody: requestBody(endpoint) } : {}),
      responses: Object.fromEntries([
        ...endpoint.successStatus.map((status) => [String(status), { description: "Success", content: { "application/json": { schema: schema(endpoint.success) } } }]),
        ...endpoint.errorStatus.map((status) => [String(status), { description: "Error", content: { "application/json": { schema: schema(endpoint.error) } } }]),
      ]),
    };
  }
  return {
    openapi: "3.1.0",
    info: { title: `v2 ${service} browser API`, version: "0.0.0" },
    components: { securitySchemes: { cookieAuth: { type: "apiKey", in: "cookie", name: "v2-auth.session_token" } } },
    paths,
  };
}

function generatedClient() {
  const lines = [
    "/* This file is generated by scripts/generate-api.mjs. Do not edit manually. */",
    "import { createApiClient, type ApiClientConfig, type ApiRequestInput } from \"./transport\";",
    "",
    "export function createGeneratedApiClient(config: ApiClientConfig) {",
    "  const client = createApiClient(config);",
    "  return {",
  ];
  for (const endpoint of apiEndpoints) {
    lines.push(`    ${endpoint.operationId}: (input?: ApiRequestInput) => client.request("${endpoint.operationId}", input),`);
  }
  lines.push("  };", "}", "");
  return `${lines.join("\n")}\n`;
}

function writeIfChanged(path, content) {
  let existing = null;
  try { existing = readFileSync(path, "utf8"); } catch {
    // file will be created
  }
  if (existing === content) return false;
  if (check) {
    console.error(`Generated API artifact is out of date: ${path}`);
    process.exitCode = 1;
    return true;
  }
  ensureDir(dirname(path));
  writeFileSync(path, content);
  return true;
}

ensureDir(generatedDir);
writeIfChanged(join(generatedDir, "core.json"), `${JSON.stringify(openApi("core"), null, 2)}\n`);
writeIfChanged(join(generatedDir, "auth.json"), `${JSON.stringify(openApi("auth"), null, 2)}\n`);
writeIfChanged(clientPath, generatedClient());
if (process.exitCode) process.exit(process.exitCode);
